[main]
tickDuration=25
attackStrategy=0
fastGame=true

[[armies]]
name="USA"

    [[armies.squads]]
        [[armies.squads.units]]
        type="Soldier"
        [[armies.squads.units]]
        type="Soldier"
    [[armies.squads]]
        [[armies.squads.units]]
        type="Vehicle"
            [[armies.squads.units.operators]]
            type="Soldier"
            [[armies.squads.units.operators]]
            type="Soldier"
            [[armies.squads.units.operators]]
            type="Soldier"
        [[armies.squads.units]]
        type="Soldier"
    [[armies.squads]]
        [[armies.squads.units]]
        type="Soldier"
        [[armies.squads.units]]
        type="Vehicle"
            [[armies.squads.units.operators]]
            type="Soldier"
            [[armies.squads.units.operators]]
            type="Soldier"
    [[armies.squads]]
        [[armies.squads.units]]
        type="Soldier"
        [[armies.squads.units]]
        type="Soldier"

[[armies]]
name="China"

    [[armies.squads]]
        [[armies.squads.units]]
        type="Soldier"
        [[armies.squads.units]]
        type="Soldier"
    [[armies.squads]]
        [[armies.squads.units]]
        type="Vehicle"
            [[armies.squads.units.operators]]
            type="Soldier"
            [[armies.squads.units.operators]]
            type="Soldier"
        [[armies.squads.units]]
        type="Soldier"

[[armies]]
name="GLA"

    [[armies.squads]]
        [[armies.squads.units]]
        type="Soldier"
        [[armies.squads.units]]
        type="Soldier"
    [[armies.squads]]
        [[armies.squads.units]]
        type="Soldier"
        [[armies.squads.units]]
        type="Soldier"
    [[armies.squads]]
        [[armies.squads.units]]
        type="Soldier"
        [[armies.squads.units]]
        type="Soldier"
    [[armies.squads]]
        [[armies.squads.units]]
        type="Soldier"
        [[armies.squads.units]]
        type="Soldier"
    [[armies.squads]]
        [[armies.squads.units]]
        type="Vehicle"
            [[armies.squads.units.operators]]
            type="Soldier"
            [[armies.squads.units.operators]]
            type="Soldier"
        [[armies.squads.units]]
        type="Vehicle"
            [[armies.squads.units.operators]]
            type="Soldier"
            [[armies.squads.units.operators]]
            type="Soldier"
    [[armies.squads]]
        [[armies.squads.units]]
        type="Vehicle"
            [[armies.squads.units.operators]]
            type="Soldier"
            [[armies.squads.units.operators]]
            type="Soldier"
        [[armies.squads.units]]
        type="Vehicle"
            [[armies.squads.units.operators]]
            type="Soldier"
            [[armies.squads.units.operators]]
            type="Soldier"
            [[armies.squads.units.operators]]
            type="Soldier"
            [[armies.squads.units.operators]]
            type="Soldier"
            [[armies.squads.units.operators]]
            type="Soldier"